<?php
require_once '../config.php';
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

$meetingDate = trim($_POST['meeting_date'] ?? date('Y-m-d'));
$chairedBy = trim($_POST['chaired_by'] ?? 'Dr. Syed Javeed');
$attendees = trim($_POST['attendees'] ?? 'Deepti, Daksha, Hansika, Pranav, Prajwal');

// Fetch open/in-progress tickets
$result = $conn->query("SELECT * FROM tickets WHERE status IN ('Open', 'In-Progress') ORDER BY ticket_id ASC");
$openTickets = [];
while ($row = $result->fetch_assoc()) {
    $openTickets[] = $row;
}

// Get summary counts
$totalResult = $conn->query("SELECT COUNT(*) as c FROM tickets");
$total = $totalResult->fetch_assoc()['c'];

$openCount = $conn->query("SELECT COUNT(*) as c FROM tickets WHERE status = 'Open'")->fetch_assoc()['c'];
$progressCount = $conn->query("SELECT COUNT(*) as c FROM tickets WHERE status = 'In-Progress'")->fetch_assoc()['c'];
$resolvedCount = $conn->query("SELECT COUNT(*) as c FROM tickets WHERE status = 'Resolved'")->fetch_assoc()['c'];
$verifiedCount = $conn->query("SELECT COUNT(*) as c FROM tickets WHERE status = 'Verified'")->fetch_assoc()['c'];

// Format meeting minutes text
$text = "═══════════════════════════════════════════\n";
$text .= "  MEETING MINUTES — FeedTrack Review\n";
$text .= "═══════════════════════════════════════════\n\n";
$text .= "Date      : $meetingDate\n";
$text .= "Chaired By: $chairedBy\n";
$text .= "Attendees : $attendees\n\n";
$text .= "───────────────────────────────────────────\n";
$text .= "  OPEN ACTION ITEMS (" . count($openTickets) . ")\n";
$text .= "───────────────────────────────────────────\n\n";

if (count($openTickets) === 0) {
    $text .= "  ✅ No open action items. All tickets resolved.\n";
} else {
    foreach ($openTickets as $i => $t) {
        $num = $i + 1;
        $text .= "  $num. [{$t['ticket_id']}] {$t['description']}\n";
        $text .= "     Dept: {$t['department']} | Priority: {$t['priority']} | Status: {$t['status']}\n";
        $text .= "     Assigned: {$t['student_name']} | Date: {$t['submission_date']}\n\n";
    }
}

$text .= "───────────────────────────────────────────\n";
$text .= "  SUMMARY\n";
$text .= "───────────────────────────────────────────\n\n";
$text .= "  Total Tickets  : $total\n";
$text .= "  Open           : $openCount\n";
$text .= "  In-Progress    : $progressCount\n";
$text .= "  Resolved       : $resolvedCount\n";
$text .= "  Verified       : $verifiedCount\n\n";
$text .= "═══════════════════════════════════════════\n";
$text .= "  Minutes auto-generated by FeedTrack\n";
$text .= "  Woxsen University, School of Technology\n";
$text .= "═══════════════════════════════════════════";

// Save to database
$stmt = $conn->prepare("INSERT INTO meeting_minutes (meeting_date, chaired_by, attendees, content) VALUES (?, ?, ?, ?)");
$stmt->bind_param('ssss', $meetingDate, $chairedBy, $attendees, $text);
$stmt->execute();
$stmt->close();

echo json_encode([
    'success' => true,
    'content' => $text
]);

$conn->close();
?>